### ISSUE TITLE
Volume script doesn't work in Ubuntu 16.04

### ISSUE THREAD

**Issue by qazip** [vivien/i3blocks#281] opened 2018-01-05 21:14 UTC
Hello,

I'm running ./volume that's located in /usr/share/i3blocks/ and I get the following output:

>Specify a scontrol identifier: 'name',index
>Specify a scontrol identifier: 'name',index

The volume is also not showing in my i3bar even though I have:

>[volume]
>label=VOL
>label=♪
>instance=Master
>#instance=PCM
>interval=once
>signal=10

in i3blocks.conf.. What am I doing wrong? Could use some help here..

**Comment by kb100** [comment] 2018-01-05 22:50
Use `command=/usr/share/i3blocks/volume "5%" default`. I think this bug is caused by an update in how pulse/alsa interact. Also, scripts are being migrated out of i3blocks and into i3blocks contrib. We already have a PR in the works to fix this issue.

https://github.com/vivien/i3blocks-contrib/pull/129

**Comment by qazip** [comment] 2018-01-06 10:19
Hey, thanks for the prompt reply.

Still doesn't work. Doing that in the terminal outputs exactly the same thing as before ("Specify a scontrol identifier..")

**Comment by jolange** [comment] 2018-01-06 13:50
Can you post the output of `pulseaudio --version`, `amixer info`, `amixer scontrols` and also try `volume "5%" default`?

**Comment by qazip** [comment] 2018-01-06 14:07
➜  ~ pulseaudio --version
pulseaudio 8.0

➜  ~ amixer info
Card default 'HDMI'/'HDA Intel HDMI at 0xf7d14000 irq 31'
  Mixer name	: 'Intel Haswell HDMI'
  Components	: 'HDA:80862807,80860101,00100000'
  Controls      : 7
  Simple ctrls  : 1

➜  ~ amixer scontrols
Simple mixer control 'IEC958',0

**Comment by kb100** [comment] 2018-01-06 19:09
@qazip Try `command=/usr/share/i3blocks/volume "5%" default` and `command=/usr/share/i3blocks/volume "5%" pulse` with `instance=IEC958`

**Comment by qazip** [comment] 2018-01-06 19:44
Hey @kb100,

Tried both of these and none of  them works.

This is how my file looks (the part pertaining to the volume): 

```
# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=/usr/share/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

# Volume indicator
#
# The first parameter sets the step (and units to display)
# The second parameter overrides the mixer selection
# See the script for details.
[volume]
command=/usr/share/i3blocks/volume "5%" pulse
# command=/usr/share/i3blocks/volume "5%" default
label=VOL
# label=♪
# instance=Master
instance=IEC958
#instance=PCM
interval=once
signal=10

```

**Comment by kb100** [comment] 2018-01-06 21:06
@qazip Let's try to go a bit lower level. Do you know of any amixer command that will toggle your device between muted and not?

The i3blocks script ultimately just calls

    amixer -q -D $MIXER sset $SCONTROL toggle

so we need to find a choice of $MIXER and $SCONTROL that work for you, then we can figure out how to determine them programmatically.

**Comment by kb100** [comment] 2018-01-06 21:13
@qazip, try

    amixer -q -D HDMI sset IEC958 toggle

**Comment by kb100** [comment] 2018-01-06 21:23
@qazip, or just

    amixer sset IEC958 toggle

**Comment by qazip** [comment] 2018-01-06 21:47
@kb100: 

➜  ~ amixer -q -D HDMI sset IEC958 toggle 
ALSA lib control.c:954:(snd_ctl_open_noupdate) Invalid CTL HDMI
amixer: Mixer attach HDMI error: No such file or directory
➜  ~ amixer sset IEC958 toggle 
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [off]
➜  ~ amixer sset IEC958 toggle 
Simple mixer control 'IEC958',0
  Capabilities: pswitch pswitch-joined
  Playback channels: Mono
  Mono: Playback [on]

On my i3config, I've the following:

bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute 1 toggle # mute sound

and it works. So pactl set-sink-mute 1 toggle works to mute.

**Comment by kb100** [comment] 2018-01-06 22:10
I see the issue, 

    SCONTROL="${BLOCK_INSTANCE:-$(amixer -D $MIXER scontrols |
                      sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p" |
                      head -n1
                    )}"

    sed -n "s/Simple mixer control '\([A-Za-z ]*\)',0/\1/p"

doesn't allow numbers in the mixer name, but your mixer name has numbers in it. This is a quick fix that I will put in i3blocks-contrib but it won't be fixed in i3blocks.

**Comment by kb100** [comment] 2018-01-06 22:11
After the fix, 

    [volume]
    command=/usr/share/i3blocks/volume "5%" default
    label=VOL
    instance=IEC958
    interval=once
    signal=10

will work

**Comment by qazip** [comment] 2018-01-07 10:46
@kb100:

I changed my volume script in /usr/share to reflect your commit. Your command doesn't work, it has to be:
command=/usr/share/i3blocks/volume "5%" pulse
instance = Master

Note the "pulse" instead of "default" and "Master" instead of "IEC958". It is now working perfectly, thanks! What interval should I use though? "once" doesn't seem very recommendable, does it? I'm using 5secs, but it feels weird.

**Comment by qazip** [comment] 2018-01-07 14:41
I noticed that it doesn't update, unless I click there. Anyway to make it automatically update, that is, when I change volume (or mute/unmute), the bar should automatically update without me needing to click in the "vol" section..

**Closed** 2018-01-07 14:43 UTC

**Comment by kb100** [comment] 2018-01-07 19:04
Glad you figured it out. See the usage section at https://github.com/vivien/i3blocks-contrib/tree/master/volume for instructions on how to get the block running by signal. Instead of polling the volume every, say, 5 seconds, signals are used to say "hey i3blocks, I just changed the volume, update my volume block now". This is more efficient and provides a more responsive experience.

This block does not support the ability to subscribe to volume change events, like https://github.com/vivien/i3blocks-contrib/tree/master/volume-pulseaudio does, so you will have to either use polling or force yourself to only change volume via scrolling on the blocklet or using the XF86 buttons on your keyboard. If you want to try the other volume block, look at the `-S` flag which subscribes to volume change events.

**Comment by qazip** [comment] 2018-01-07 19:16
@kb100.

The code in the frontpage of your first link (https://github.com/vivien/i3blocks-contrib/tree/master/volume) works perfectly, without needing to change anything. It was copy paste and now, whenever I change volume/mute, it changes automatically in the bar. Fantastic! And this is more efficient you say? Great. Thank you very much!
