### ISSUE TITLE
default colors ignored

### ISSUE THREAD

**Issue by marklee77** [vivien/i3blocks#174] opened 2016-02-23 01:05 UTC
the sept 30 commit to not ignore blank lines in blocklet output means that any default colors specified in the config file get ignored.

**Comment by digijap** [comment] 2016-02-23 22:48
@marklee77 Do you have a workaround or something like that already? I'm having the same issue. Btw I think that this is a duplicate of [#146](https://github.com/vivien/i3blocks/issues/146)

**Comment by marklee77** [comment] 2016-02-24 09:22
for the moment I just checked out the version one before that commit. I guess the question is what is the appropriate behavior? Right now the problem is that if the line is empty then it just copies that value to the color property without any checks. We could put in a read to a temporary variable, and then copy if the strlen is greater to 0, but that would make the behavior for color inconsistent with text and short_text. Not sure if that's important.

**Comment by Johney16** [comment] 2016-02-28 18:14
Can confirm. Using version 1.4, color function does not seem to work in i3blocks confi file. Previous fixes/patches are implemented, but issue persists. Using Ubuntu 14.04. 

Making color changes in each individual blocklet-script does indeed change the output color.

**Comment by vivien** [comment] 2018-09-10 13:33
I hope you get the expected behavior by now, otherwise feel free to reopen the issue.

**Closed by vivien** 2018-09-10 13:33 UTC
