### ISSUE TITLE
Colors not showing in bar

### ISSUE THREAD

**Issue by pr0letariat** [vivien/i3blocks#173] opened 2016-02-19 11:45 UTC
Hi,

I have added colors to my blocks as shown in my config file below.

Unfortunately none of these colors are showing in my bar.

Can anyone help? Any more information needed, let me know.

[i3-blocks.conf.txt](https://github.com/vivien/i3blocks/files/137875/i3-blocks.conf.txt)

**Comment by sasanjac** [comment] 2016-02-19 17:27
Try if they are showing if you set `interval=-3`. I have the same problem

**Comment by pr0letariat** [comment] 2016-02-19 18:16
@sasanjac Thanks, that worked!

**Comment by sasanjac** [comment] 2016-02-19 18:18
@pr0letariat Yes, but now your block isn't updating anymore. Something is broken I think, I was just checking, if you have the same problem as me.

**Comment by digijap** [comment] 2016-02-23 22:45
@sasanjac @pr0letariat I think this is a duplicate of [#146](https://github.com/vivien/i3blocks/issues/146). You can check the progress on there

**Comment by 123maxmix123** [comment] 2017-02-10 18:23
color=#... //works only sometimes, sometimes not
background=#... //not works at all, i mean it accepts it but does nothing, even with forks
border=#...
border_top / left/right/... //also this doesnt do any result

I'm trying i3wm on ubuntu16.04

**Comment by 123maxmix123** [comment] 2017-02-11 12:52
markup=pango
works only with direct plain text, but when i try to apply it to the output of external script its not working anymore.
further, if i try to add custom colored text before another module, the text is displayed in the end of panel but not before that command.

**i3blocks.conf example**

# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# background
# border
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
#
# The top properties below are applied to every block, but can be overridden.
# Each block command defaults to the script name to avoid boilerplate.
command=~/.config/i3/i3blocks/$BLOCK_NAME
separator_block_width=15
markup=none

#NOT WORKS even inside some blocks or global
background=#ffffff

# current ip
[ip-address]
label=IP:
interval=300

# Language indicator
[layout_switch.sh]
label=LANG:
interval=once
signal=1

# Date Time
[time]
color=#c3ff00
command=date '+%Y-%m-%d %H:%M'
interval=60

# Volume controller
[volumeicon.sh]
label=Volume:
interval=once

------------------------------------
BUT in i3wm config if i set panel colors it works, i tried to delete this to see if it owerrides somehow, i3blocks settings, but nothing.
I tried to to install i3blocks (v1.4-3) but still same problems
By the way volumeicon cant be loaded in i3wm config, but i managed that it loads if i put it in i3blocks config file.
volumeicon.sh contains just command volumeicon.

bar {        
        status_command i3blocks -c ~/.config/i3/i3blocks.conf
        
        tray_output primary
        position top
        
        colors {
	    separator #000000
	    background #9299a3
	    statusline #000000
	    focused_workspace #b22d21 #baef86 #ffffff
	    active_workspace #fdf6e3 #6c71c4 #fdf6e3
	    inactive_workspace #002b36 #586e75 #ffffff
	    urgent_workspace #d33682 #d33682 #fdf6e3
	}
        
}

**Comment by kb100** [comment] 2017-02-11 14:56
I think you don't understand by what pango formatting is. Using `markup=pango` tells i3blocks to expect output of the script to be pango formatted, e.g. `<span color='red'>error!</span>` will show "error!" in red. You cannot put `markup=pango` on a blocklet that does not use pango. Probably what you *actually* want is to use the preexisting pango-ready scripts in https://github.com/vivien/i3blocks-contrib instead of rewriting blocks that already exist.

**Closed** 2018-09-10 13:31 UTC
