### ISSUE TITLE
Clicks are not detected

### ISSUE THREAD

**Issue by klaxa** [vivien/i3blocks#66] opened 2014-11-19 21:28 UTC
For some reason clicks are not detected on my system. The SIGIO signal is never received.
I used the latest master from github, see https://gist.github.com/klaxa/34f97e5c1829b86a1da9 for configurations and logs.

**Comment by vivien** [comment] 2015-02-10 19:42
Hi @klaxa,

Sorry for the delay. I did some tests and can actually reproduce some weird behavior with your configs. I'm wondering if the bug is not from i3bar itself, given https://github.com/i3/i3/issues/1458. I didn't try @airblader's patch yet, I'll try to do it asap.

**Comment by Airblader** [comment] 2015-02-10 19:45
Haven't tried these configs, but what exactly happens? No click at all? i3/i3#1458 is only about the click area being offset from the actual button. Clicks itself do work.

**Comment by vivien** [comment] 2015-03-09 04:37
Hi @klaxa,

With the latest master, I'm not able to reproduce your issue, or any weird behavior. I'm closing the issue.
Can you give it another try, and feel free to reopen it if there's anything wrong.

Thanks!

**Closed by vivien** 2015-03-09 04:37 UTC

**Comment by klaxa** [comment] 2015-03-15 20:00
Sorry for the late reply as only today I started to configure i3blocks again. Button clicking works properly now. Thanks!
