### ISSUE TITLE
Handling line-buffered block output without respawning

### ISSUE THREAD

**Issue by Zopieux** [vivien/i3blocks#85] opened 2015-01-28 11:11 UTC
Hello,

Currently blocks can either be respawn when they exit or be executed at a specific interval. While this works well for things like a clock, load average or `du`, I can think of many blocks that are *event-driven* meaning their output is constant until something happens:

* pulseaudio volume changes
* the next song is played in MPD 
* MPD is paused/resumed
* brightness changes

Small examples of such "observers" can be found in [this project I'm working on](https://bitbucket.org/Zopieux/i3asyncstatus/src/master/clib/), which is basically a lesser-i3blocks with support for this feature. I would happily throw that away if i3blocks could support buffered output without using signals that have serious limitations.

With the current implementation, we cannot use a blocking process that would produce lines of output when something happens. We have to exit so i3blocks can read & display the output. It would be great to have something like `interval=once` that would `select()` and read a single line when stdout becomes readable. I am willing to work on this feature myself, but I am unsure where to start. The event loop is completely `sigwaitinfo`-based and I don't see where I could fit the (blocking) `select()` or something like that.

**Comment by vivien** [comment] 2015-01-29 08:31
Hi!

> Small examples of such "observers" can be found in this project I'm working on, which is basically a lesser-i3blocks with support for this feature. I would happily throw that away if i3blocks could support buffered output without using signals that have serious limitations.

What are the limitations of the real-time signals?

> With the current implementation, we cannot use a blocking process that would produce lines of output when something happens. We have to exit so i3blocks can read & display the output. It would be great to have something like interval=once that would select() and read a single line when stdout becomes readable. I am willing to work on this feature myself, but I am unsure where to start. The event loop is completely sigwaitinfo-based and I don't see where I could fit the (blocking) select() or something like that.

This is not complex to implement in the scheduler loop. I already thought about this behavior, but decided not to do that because the problem is elsewhere:

  * How do you distinguish if the process outputs 1, 2 or 3 lines? (full_text and short_text and/or color)
  * How to you inform i3blocks about an urgency?
  * Should i3blocks care if the process terminates?

Adding a delimiter would be non-intuitive IMO.
I may add support for other formats (ini, oneline-json or default plain (the 3 lines thing)), but it is not planned yet.

----

For blocking commands which output continuously changes (e.g. `dbus-monitor --monitor`, `inotifywait -m` or `tail -f`), I strongly recommend writing a simple external daemon. i3 makes it really convenient to spawn them. From the i3 config:

````
bar {
  status_command i3blocks
}

# My daemons (see also "exec_always")
exec ~/bin/blocklets/foobard
````

The daemon can wait for an event (like MPD changes) and then notifies i3blocks to execute an action (like `mpc current`). Or it can output its data to a cache file, then 2 options are offered to update the block: either the daemon signals the block to read the file[1], or the block can listen to write event on the cache file[2].

[1] dump a file on signal:
```` ini
[text from foobar daemon]
command=cat ~/.cache/blocklets/foobar
interval=once
signal=20
````

[2] wait for writes and dump the file:
```` ini
[text from foobar daemon]
full_text=waiting a change from foobar
command=inotifywait -qq -e close_write /tmp/foobar && cat /tmp/foobar
interval=repeat
````

----

For changes from keys, you may want to bind and notify i3blocks from within the i3 config, especially with the handy `--release` bindsym option. For instance, here's a trivial backlight blocklet.

In the i3 config:

````
# Optional increase/decrease, if not already handled by your distro
#bindsym XF86MonBrightnessUp             exec xbacklight -inc 10
#bindsym XF86MonBrightnessDown           exec xbacklight -dec 10
bindsym --release XF86MonBrightnessUp   exec pkill -SIGRTMIN+22 i3blocks
bindsym --release XF86MonBrightnessDown exec pkill -SIGRTMIN+22 i3blocks
````

the blocklet in the i3blocks config:

```` ini
[backlight]
label=☀
command=xbacklight -get | sed 's,\..*,%,'
interval=once
signal=22
````

----

Only an eventual oneline format would make this feature possible. But while the asynchronousity was really a need for slow commands, I'm not sure that making i3blocks handle long running processes (i.e. daemons) is a good thing.

**Comment by Zopieux** [comment] 2015-01-29 12:35
Firs of all, thanks for your extensive answer with lots of useful info.

> What are the limitations of the real-time signals?

No a limitation in themselves, but still: I was referring to the rather low number of available signals and the fact we have to reference them in two different places, so it's easy to make mistakes.

---

If you were to add a specific input format, I would totally advise the use of a simple serialization format so we can pass any kind of options to i3bar, not only *short_text* or *color* (there are also *align*, *width*, etc. that are pretty useful). You could also give an *urgent* flag this way. JSON seems great at it is simple and already used by i3bar itself.

---

I understand you do not want to add this kind of complexity to the current implementation, although I must say I am not a big fan of using temporary files for this kind of stuff, where we could have the program simply redirect stdout without the need for neither signals nor arbitrary named temporary files messing around.

I will try to work on something and come back to this thread if I reach any success.

**Comment by vivien** [comment] 2015-01-29 15:50
> > What are the limitations of the real-time signals?

> No a limitation in themselves, but still: I was referring to the rather low number of available signals and the fact we have to reference them in two different places, so it's easy to make mistakes.

You have about 31 real-time signals on Linux, they are queueable (which guarantees that i3blocks will handle 2 signals if you pkill twice), and prioritized, which allows the user to manage which block must be updated first if they update in the same loop iteration (this is hardly feasible without these signals).

I like the cache files since they may be persistent over i3 restarts (like daemons with `exec`) and just `cat` them makes really trivial blocklets.

My priorities for the moment is to get clean scripts (there's several PR here), add tests, then implement the different formats so these cache files can update urgency and such as you correctly mentioned (I don't have any use case yet for changing the *align* or *separator* properties at runtime, but why not as the implementation is trivial?).

Anyway I get your point and as the support for persistent commands (with mandatory oneline output) is simple, I am willing to add this feature once the points above are done if people feel the need for it.

**Comment by Zopieux** [comment] 2015-01-29 18:05
Yeah, I guess 31 signals can be enough actually.

I spent the afternoon working on a quick prototype. You may want to give it a look, any feedback is greatly appreciated. I won't open a PR for now, except if you want me to. The changes are not really disruptive, I replaced `sigwaitinfo()` with `select()` and used `signalfd` to handle signals as before.

https://github.com/Zopieux/i3blocks/tree/blocking-interval ([show diff](https://github.com/Zopieux/i3blocks/commit/e7d9c8f233ba09e3551ce227f849129412e59773))

Thanks for your time and dedication.

**Comment by vivien** [comment] 2015-02-11 00:29
Hi @Zopieux,

Basically to implement that, you'll want to set the fd non-blocking and do signal-driven I/O (which associates a signal to a fd and asks the kernel to trigger it when the fd is ready) on block stdout pipe read ends. Using a real-time signal (SIGRTMIN which has the maximum priority, wasn't used yet) ensures that you won't miss any lines. Then `sigwaitinfo()` is able to tell you which fd triggered that signal.

I've pushed a branch for that, I'll review it again and do some adjustments before merging it into master. See: https://github.com/vivien/i3blocks/commit/ac80a2ffda0e6e588b0a86d74e4bc940f42e436f#diff-da1fe2b4f26525ab43e1476ed51c23d8L163

You can actually give it a try if you like, it currently supports only plain text format (i.e. the `full_text`).
I'll review you work on JSON format and will try to adapt some of it.

BTW, I have this question: do you think that it could be a real use case to have a persistent block which eventual exits?

**Comment by Zopieux** [comment] 2015-02-11 13:30
Hello @vivien,

Thanks for your commitment on that issue! Your implementation shares some concepts with mine, except I used `signalfd` with `select()` and you chose the other way around (signal-driven I/O). :smiley: I'll give it a try for sure.

> do you think that it could be a real use case to have a persistent block which eventual exits?

To me, a *persistent* block only *exists* when it encounters an error, and in this case it should behave the same way than standard blocks: urgent error message. If it exits with return code 0, maybe we could start it again, but that would require a backoff delay to prevent hogging the scheduler. In this case we could have a `restart_after` option, maybe.

**Comment by vivien** [comment] 2015-02-25 17:42
I merged the generic part of the persistent branch, which is now a single commit, about to be merged soon too.

**Comment by vivien** [comment] 2015-03-08 22:28
i3blocks now supports the following block:

```` ini
[date]
command=while :; do date +'{"full_text": "%s"}'; sleep 1; done
interval=persist
format=json
````

Closing the issue, thanks!

**Closed by vivien** 2015-03-08 22:28 UTC

**Comment by Zopieux** [comment] 2015-03-09 18:00
# `\o/`

**Comment by isinaltinkaya** [comment] 2018-09-21 20:13
> For changes from keys, you may want to bind and notify i3blocks from within the i3 config, especially with the handy `--release` bindsym option. For instance, here's a trivial backlight blocklet.
> 
> In the i3 config:
> 
> ```
> # Optional increase/decrease, if not already handled by your distro
> #bindsym XF86MonBrightnessUp             exec xbacklight -inc 10
> #bindsym XF86MonBrightnessDown           exec xbacklight -dec 10
> bindsym --release XF86MonBrightnessUp   exec pkill -SIGRTMIN+22 i3blocks
> bindsym --release XF86MonBrightnessDown exec pkill -SIGRTMIN+22 i3blocks
> ```
> 
> the blocklet in the i3blocks config:
> 
> ```ini
> [backlight]
> label=☀
> command=xbacklight -get | sed 's,\..*,%,'
> interval=once
> signal=22
> ```
> 
> Only an eventual oneline format would make this feature possible. But while the asynchronousity was really a need for slow commands, I'm not sure that making i3blocks handle long running processes (i.e. daemons) is a good thing.

I tried this one, it works but it always shows the previous brightness level.
For instance: I changed from 0 to 10 and it shows 0, then 10 to 20 and it shows 10.
