### ISSUE TITLE
Removing last newline character from i3blocks.conf breaks i3blocks

### ISSUE THREAD

**Issue by gadelat** [vivien/i3blocks#27] opened 2014-06-08 19:25 UTC
i3blocks.conf ends with LF char. If you remove it, i3blocks won't start and outputs following error log instead:
```
line "interval=1" is not terminated by a newline
*** Error in `i3blocks': free(): invalid pointer: 0x00000000012830f8 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x73f8e)[0x7f26b4d59f8e]
/usr/lib/libc.so.6(+0x7988e)[0x7f26b4d5f88e]
/usr/lib/libc.so.6(+0x7a04b)[0x7f26b4d6004b]
i3blocks[0x4020be]
i3blocks[0x4019e1]
i3blocks[0x401a3f]
i3blocks[0x40121d]
/usr/lib/libc.so.6(__libc_start_main+0xf0)[0x7f26b4d06000]
i3blocks[0x401294]
======= Memory map: ========
00400000-00404000 r-xp 00000000 08:06 1281530                            /usr/bin/i3blocks
00603000-00604000 r--p 00003000 08:06 1281530                            /usr/bin/i3blocks
00604000-00605000 rw-p 00004000 08:06 1281530                            /usr/bin/i3blocks
01282000-012a3000 rw-p 00000000 00:00 0                                  [heap]
7f26b4ad0000-7f26b4ae6000 r-xp 00000000 08:06 1186197                    /usr/lib/libgcc_s.so.1
7f26b4ae6000-7f26b4ce5000 ---p 00016000 08:06 1186197                    /usr/lib/libgcc_s.so.1
7f26b4ce5000-7f26b4ce6000 rw-p 00015000 08:06 1186197                    /usr/lib/libgcc_s.so.1
7f26b4ce6000-7f26b4e8a000 r-xp 00000000 08:06 1182970                    /usr/lib/libc-2.19.so
7f26b4e8a000-7f26b508a000 ---p 001a4000 08:06 1182970                    /usr/lib/libc-2.19.so
7f26b508a000-7f26b508e000 r--p 001a4000 08:06 1182970                    /usr/lib/libc-2.19.so
7f26b508e000-7f26b5090000 rw-p 001a8000 08:06 1182970                    /usr/lib/libc-2.19.so
7f26b5090000-7f26b5094000 rw-p 00000000 00:00 0 
7f26b5094000-7f26b50b5000 r-xp 00000000 08:06 1182947                    /usr/lib/ld-2.19.so
7f26b526c000-7f26b526f000 rw-p 00000000 00:00 0 
7f26b52b2000-7f26b52b4000 rw-p 00000000 00:00 0 
7f26b52b4000-7f26b52b5000 r--p 00020000 08:06 1182947                    /usr/lib/ld-2.19.so
7f26b52b5000-7f26b52b6000 rw-p 00021000 08:06 1182947                    /usr/lib/ld-2.19.so
7f26b52b6000-7f26b52b7000 rw-p 00000000 00:00 0 
7fff3eb34000-7fff3eb55000 rw-p 00000000 00:00 0                          [stack]
7fff3ebfe000-7fff3ec00000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```

**Comment by vivien** [comment] 2015-03-09 04:45
Closing this since I cannot reproduce it. Feel free to reopen if you have an example to give.

**Closed by vivien** 2015-03-09 04:45 UTC
