### ISSUE TITLE
Pango 1:1.44-1 Spacing Issue

### ISSUE THREAD

**Issue by blackace306** [vivien/i3blocks#387] opened 2019-07-28 02:33 UTC
I recently updated pango to to version 1:1.44-1 on my Arch system. Now all of my i3blocklets have a massive amount of space between the label and the actual information the blocklet displays. I have temporarily fixed the issue by downgrading pango to the previous version for now. I have attached a screenshot to show exactly what is going on. I do apologize if this has already been addressed or in the works. I could not find this issue in the forum here. Thanks in advanced for any help you can offer. 
![Screenshot_2019-07-27_22-26-45](https://user-images.githubusercontent.com/13664894/62001426-41756c00-b0be-11e9-946e-6a4ac1fc1e9d.png)

**Comment by ToraNova** [comment] 2019-07-28 14:57
I am also having the same issue also on 1:1.44-1
![pic-selected-190728-2256-39](https://user-images.githubusercontent.com/26948113/62008920-1efd5480-b18b-11e9-89b4-63e9065a99e9.png)

**Comment by Pottenstein** [comment] 2019-07-28 17:38
i have the same issue

**Comment by blackace306** [comment] 2019-07-28 17:54
I wasn't sure if the issue is on pango's side or i3blocks side. I posted the issue here just to get some light on it. I just downgraded pango and put my /etc/pacman.conf to ignore pango for now. Until a fix comes through I guess. Works for now.

**Comment by gzugmeyer** [comment] 2019-07-29 06:37
I have the same problem, and I'm not using i3blocks, but an home made script to do the same. It seems to not be an issue with i3blocks.

downgrading pango package works for me too.

**Comment by gzugmeyer** [comment] 2019-07-29 06:43
The new version of pango 1.44.1 fix the issue ...

**Comment by blackace306** [comment] 2019-07-29 15:16
Awesome, it looks like pango in the Arch repos got updated to that version just today 7/29. I updated, it is working again. Thanks a lot. Do I have to mark this solved or something?

**Comment by ephos** [comment] 2019-07-31 22:12
Came here to report the issue - saw the issue and updated Pango to 1.44.1, can confirm the issue is resolved!!!

**Comment by maximtrp** [comment] 2019-08-02 09:15
I'm still having [black vertical lines](https://imgur.com/DuiViLq) that frame the Font Awesome icons with the updated pango (1.44.1). But, obviously, it is related to pango.

**Comment by vivien** [comment] 2019-08-05 21:44
That is indeed Pango-specific and not related to i3blocks. I'm glad to see that it is fixed with 1.44.1 though ;-)

**Closed by vivien** 2019-08-05 21:44 UTC
