### ISSUE TITLE
Scrolling to change workspaces isn't working on Sway

### ISSUE THREAD

**Issue by Aetheryx** [vivien/i3blocks#274] opened 2017-12-17 10:59 UTC
Hi there,
I recently moved to Sway and now whenever I scroll on my bar, nothing happens. On i3 this used to scroll through the workspaces. Is this intended?

**Comment by kb100** [comment] 2017-12-18 03:41
I doubt this is intended behavior in sway. Sway is a pre-release project that has many known bugs. I am aware of several known mouse scrolling related bugs in sway, many of which have been fixed in the most recent version, but some of which are still open. This is definitely a sway/swaybar issue, not an i3bar issue or an i3blocks issue, because, as you say, it worked when you used i3. The people at sway are very friendly and I'm sure they would appreciate if you made this bug report over there. My guess is that sway is dropping mouse inputs on the bar for some unknown reason. Make sure to tell them as much information about your setup as possible including what version of sway/swaybar you are using, what distro and kernel you are using, and any other info that might help them debug this issue for you. If you are comfortable with git and compiling sway yourself, probably the most helpful thing for them would be to know if scrolling on your bar *ever* worked, and if so, exactly what commit it *stopped* working. Look up a tutorial on `git bisect` for how to do this.

**Comment by Aetheryx** [comment] 2017-12-18 07:56
I should have mentioned; I am using i3blocks. Not swaybar.

**Comment by Aetheryx** [comment] 2017-12-18 08:08
Setting `click_events` to `false` [here](https://github.com/vivien/i3blocks/blob/master/src/main.c#L35) fixes the issue.

**Comment by kb100** [comment] 2017-12-18 08:36
@Aetheryx, i3blocks is not a bar, it just talks to the bar. My guess is you are using sway+i3bar+i3blocks or sway+swaybar+i3blocks. You must be using either i3bar or swaybar (or some other bar), otherwise no bar would appear at all. i3blocks just tells the bar what to display, it plays no role in drawing the bar itself. Since setting click_events to false fixes the issue, it appears that sway is incorrectly parsing the click_events boolean. Obviously, if you want click events, click_events should be true, not false. This is all information that the sway people can use to resolve the issue on their end.

**Comment by Aetheryx** [comment] 2017-12-18 08:48
Ohh, I see. Good to know, thanks.

**Closed** 2018-09-10 19:44 UTC
