### ISSUE TITLE
error when executing i3blocks v1.3

### ISSUE THREAD

**Issue by LeonardKoenig** [vivien/i3blocks#79] opened 2015-01-14 13:49 UTC
Hello,
I'm using the i3blocks pkg from the AUR [url]https://aur.archlinux.org/packages/i3blocks[/url].
Without any changes I just tried to execute it, but I get this error:

> ERROR ini_load:247: fopen: No such file or directory
> ERROR main:75: Try 'i3blocks -h' for more information.

But this is only the case in release v1.3 - the git version does work.

**Comment by Nycroth** [comment] 2015-01-14 14:52
Yep, I just reproduced this. The problem is that i3blocks isn't finding the /etc config file with the 1.3 installation. To correct this, copy `/etc/i3blocks.conf` to `~/.config/i3blocks/config` or `~/.i3blocks.conf`. You likely don't want the default config anyway; unless you use eth0 and wlan0 for example.

**Comment by LeonardKoenig** [comment] 2015-01-14 17:11
That was my first guess, too but it didn't seem to work back than, but probably I made a typo or somewhat as it works now (tried again). Anyway, I'm now on i3blocks-git, it only takes ~10secs to compile, so there's no problem :P

Thanks for the answer, should I close it now or wait for a fix?

**Comment by Nycroth** [comment] 2015-01-14 17:46
I'd wait for @vivien to close this one. He may want to release a v1.3.1 to fix this so I'll leave that in his court.

**Comment by Powersource** [comment] 2016-04-04 16:19
I'm on 1.4 and just FYI I got this error right after installing and enabling it. Worked after copying the config though.

**Comment by kb100** [comment] 2016-04-04 18:52
@vivien It seems this issue never got resolved, you may want to take another look.

**Comment by Nixpower** [comment] 2016-05-23 17:45
I am also on 1.4 and I am getting a similar issue.

**Comment by vivien** [comment] 2016-07-26 21:54
Hi all, that's a Arch AUR specific issue (in the PKGBUILD build command). I've submitting a fix for it: https://aur.archlinux.org/packages/i3blocks (comment)
Thanks!

**Comment by vivien** [comment] 2016-07-27 18:24
The AUR package i3blocks 1.4-3 is released with the fix, closing the issue.

**Closed by vivien** 2016-07-27 18:24 UTC
