### ISSUE TITLE
[next] branch broken? Simple block echoing a number crashes

### ISSUE THREAD

**Issue by kb100** [vivien/i3blocks#311] opened 2018-08-23 05:39 UTC
I just built and installed `3bde4b223b33a5e2122983b68486a6be75b3e680`. Firstly there was a lot of confusion as there was a forced update at some point so this required hard resetting to checkout. But anyway the following block fails!

    [test]
    command=echo "5"
    interval=1

i3blocks writes nothing to stderr. i3bar complains with 'SPEC VIOLATION full_text is NULL!"

Even stranger, the following block does not fail

    [test]
    command=echo "a"
    interval=1

Running i3blocks from the command line shows the difference:

    {"version":1,"click_events":true}
    [[]
    ,[{"full_text":""}]
    ,[{"full_text":""},{"":"","name":"test","command":"echo \"5\"","interval":1,"full_text":5}]
    ^C%                    

versus

    {"version":1,"click_events":true}
    [[]
    ,[{"full_text":""}]
    ,[{"full_text":""},{"":"","name":"test","command":"echo \"a\"","interval":1,"full_text":"a"}]
    ^C%    

Apparently i3blocks is not quoting numbers? I think the issue is deeper though. I found this while attempting to update the time blocklet in i3blocks-contrib to the next branch standards. There a similar thing was happening where the full_text variable would be mal-formated, producing an output like 

    {..., "full_text": "12:34" "(Brazil}

when the script actually outputted "12:34 (Brazil)". For some reason  quotes are added at word boundaries. Presumably memory is malloced exactly as needed, so two extra quotes explains why the output is missing exactly two characters, namely `)"` before the closing brace.

**Comment by kb100** [comment] 2018-08-23 17:00
See this gist: https://gist.github.com/kb100/ff5d44911d3a474aa27cf3ab0eb69eff. 

Running from command line: 

    BLOCK_BUTTON=1 STRFTIME_FORMAT="%Y-%m-%d %H:%M" TZONES="Brazil/East,Australia/Brisbane" TZ_LABELS=Brazile,AU interval=1 ./time


Works just fine. But


    [timezones]
    command=/path/to/time
    STRFTIME_FORMAT="%Y-%m-%d %H:%M:%S"
    TZONES="Brazil/East,Australia/Brisbane,Asia/Calcutta"
    TZ_LABELS="Brazil,AU,Hyderabad"
    interval=1

Shows no output on the bar and gives malformed output

    {..., "full_text":"2018-08-23 16:58:45" "Brazil}

**Comment by vivien** [comment] 2018-08-23 19:44
That is because the values parsed from the config file are byte-for-byte what come right after the `=` signs. So you have quotes included from STRFTIME_FORMAT concatenated to `"Brazil` which is the first value split with the `/` character from TZONES.

Omitting the explicit quotes fixes the problem:

````ini
[timezones]
command=/path/to/time
STRFTIME_FORMAT=%Y-%m-%d %H:%M:%S
TZONES=Brazil/East,Australia/Brisbane,Asia/Calcutta
TZ_LABELS=Brazil,AU,Hyderabad
interval=1
````

For the former issue, using the plain text format and echoing a valid number as the *full_text* currently print it as is. I guess I'll have to make things a bit smarter here...

**Comment by kb100** [comment] 2018-08-23 20:48
Ahh I see, I need to be more careful about quoting in the future. This explains the quoting issue, but does your explanation also explain why the output is malformed? Even if my block wants to output garbage with quotes in it, i3blocks should never pass invalid output to i3bar, correct?

**Comment by vivien** [comment] 2018-09-04 04:58
I've pushed the [dynamic-properties](https://github.com/vivien/i3blocks/tree/dynamic-properties) branch which includes the next stuffs and a new error messages handling. A simple number as the *full_text* is not quoted yet, I still have to figure out how to support that in a clean way. I'll merge it soon to master once it's fixed if there's no complains.

**Comment by vivien** [comment] 2018-09-06 05:16
The issue is now fixed in the dynamic-properties branch. The commits need a bit of cleanup but the branch is mostly ready to be merged in master soon.

**Closed** 2018-09-06 21:41 UTC
